# Generated by Django 3.2 on 2021-04-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='first_model',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
